pages:
  tags:
    - runner3
  image: alpine:latest
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html style.css public/
    - cp -r src public/
  artifacts:
    paths:
      - public
  only:
    - develop


